src/java/pojo/Diak.java
package pojo;
// Generated Mar 31, 2015 12:03:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diak generated by hbm2java
 */
@Entity
@Table(name="diak"
    ,catalog="benedekTankonyv"
)
public class Diak  implements java.io.Serializable {


     private Integer id;
     private String nev;
     private String om;
     private Set<Diakosztalyev> diakosztalyevs = new HashSet<Diakosztalyev>(0);

    public Diak() {
    }

    public Diak(String nev, String om, Set<Diakosztalyev> diakosztalyevs) {
       this.nev = nev;
       this.om = om;
       this.diakosztalyevs = diakosztalyevs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nev", length=100)
    public String getNev() {
        return this.nev;
    }
    
    public void setNev(String nev) {
        this.nev = nev;
    }

    
    @Column(name="om", length=11)
    public String getOm() {
        return this.om;
    }
    
    public void setOm(String om) {
        this.om = om;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="diak")
    public Set<Diakosztalyev> getDiakosztalyevs() {
        return this.diakosztalyevs;
    }
    
    public void setDiakosztalyevs(Set<Diakosztalyev> diakosztalyevs) {
        this.diakosztalyevs = diakosztalyevs;
    }




}

src/java/tankonyv/DiakBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tankonyv;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.Set;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import org.hibernate.mapping.Collection;
import pojo.Diak;
import pojo.Diakkonyv;
import pojo.Diakosztalyev;
import pojo.Konyv;

/**
 *
 * @author nbalazs
 */
@ManagedBean(name = "diakBean")
@SessionScoped
public class DiakBean {

    @ManagedProperty(value = "#{konyvBean}")
    private KonyvBean konyvBean;
    
    private String kivalasztottEvDiaklistazashoz;
    private List<Diakosztalyev> evekDiaklistazashoz;
    private String kivalasztottOsztalyDiaklistazashoz;
    private List<Diakosztalyev> osztalyokDiaklistazashoz;

    private Diakkonyv kivalasztottDiakKonyv;
    private Diakosztalyev kivalasztottDiakOsztalyEv;
    private Dao dao;
    private Diak kivalasztottDiak;
    private List<Diak> diakok;
    private DataModel<Diakkonyv> diakkonyvek;
//    private List<Diakosztalyev> diakOsztalyEvek;
//    private List<Diakkonyv> diakKonyvek;

    public List<Diak> updateDiakok() {
        if (kivalasztottEvDiaklistazashoz == null) {
            System.out.println("Egyik");
            diakok = dao.getDiakok();
        } else if (kivalasztottOsztalyDiaklistazashoz == null) {
            System.out.println("Masik");
            diakok = dao.getDiakok(kivalasztottEvDiaklistazashoz);
        } else {
            System.out.println("Harmadik");
            diakok = dao.getDiakok(kivalasztottEvDiaklistazashoz, kivalasztottOsztalyDiaklistazashoz);
        }
        
        return getDiakok();
    }

    //property
    public List<Diakosztalyev> getDiakOsztalyEvekDiaklistazashoz() {
        return osztalyokDiaklistazashoz;
    }

    public String getKivalasztottOsztalyDiaklistazashoz() {
        return kivalasztottOsztalyDiaklistazashoz;
    }

    public void setKivalasztottOsztalyDiaklistazashoz(String kivalasztottOsztalyDiaklistazashoz) {
        this.kivalasztottOsztalyDiaklistazashoz = kivalasztottOsztalyDiaklistazashoz;
        kivalasztottDiak = null;
        updateDiakok();
    }

    

    public String getKivalasztottEvDiaklistazashoz() {
        return kivalasztottEvDiaklistazashoz;
    }

    public void setKivalasztottEvDiaklistazashoz(String kivalasztottEvDiakListazashoz) {
        this.kivalasztottEvDiaklistazashoz = kivalasztottEvDiakListazashoz;
        if (kivalasztottEvDiakListazashoz == null) {
            this.osztalyokDiaklistazashoz = null;
        } else {
            this.osztalyokDiaklistazashoz = dao.getDiakosztalyevek(kivalasztottEvDiakListazashoz);
        }
        kivalasztottDiak = null;
        updateDiakok();
    }

    public List<Diakosztalyev> getEvekDiaklistazashoz() {
        evekDiaklistazashoz = dao.getDiakosztalytanevek();
        return evekDiaklistazashoz;
    }

    public KonyvBean getKonyvBean() {
        return konyvBean;
    }

    public void setKonyvBean(KonyvBean konyvBean) {
        this.konyvBean = konyvBean;
    }

    public DataModel<Diakkonyv> getDiakkonyvek() {
        if (kivalasztottDiakOsztalyEv != null && kivalasztottDiakOsztalyEv.getTanev() != null) {
//            System.out.println(kivalasztottDiakOsztalyEv.getTanev());
            List<Diakkonyv> list = dao.getDiakkonyvek(kivalasztottDiakOsztalyEv);
            diakkonyvek = new ListDataModel<Diakkonyv>(list);
            return diakkonyvek;
        }
        if (kivalasztottDiak != null) {
//            System.out.println(kivalasztottDiak.getNev());
            List<Diakkonyv> list = dao.getDiakkonyvek(kivalasztottDiak);
            diakkonyvek = new ListDataModel<Diakkonyv>(list);
            return diakkonyvek;
        }
        return new ListDataModel<>();
    }
//    
//    public DataModel<Diakkonyv> getDiakkonyvsModel(){
//        
//    }

    public Integer getKivalasztottDiakKonyvId() {
        if (kivalasztottDiakKonyv == null) {
            return null;
        } else {
            return kivalasztottDiakKonyv.getId();
        }
    }

    public void setKivalasztottDiakKonyvId(Integer kivalasztottDiakKonyvId) {
        if (kivalasztottDiakKonyv != null) {
            this.kivalasztottDiakKonyv = dao.getDiakkonyv(kivalasztottDiakKonyvId);
        } else {
            this.kivalasztottDiakKonyv = null;
        }
    }

    public Diakkonyv getKivaloasztottDiakkonyv() {
        return kivalasztottDiakKonyv;
    }

    public void setKivaloasztottDiakkonyv(Diakkonyv kivaloasztottDiakkonyv) {
        this.kivalasztottDiakKonyv = kivaloasztottDiakkonyv;
    }

    public Integer getKivalasztottDiakOsztalyevId() {
        if (kivalasztottDiakOsztalyEv == null) {
            return null;
        } else {
            return kivalasztottDiakOsztalyEv.getId();
        }
    }

    public void setKivalasztottDiakOsztalyevId(Integer kivalasztottDiakOsztalyevId) {
        if (kivalasztottDiakOsztalyevId != null) {
            this.kivalasztottDiakOsztalyEv = dao.getDiakosztalyev(kivalasztottDiakOsztalyevId);
        } else {
            this.kivalasztottDiakOsztalyEv = null;
        }
    }

//    public List<Diakosztalyev> getDiakOsztalyEvek() {
//        return diakOsztalyEvek;
//    }
//
//    public void setDiakOsztalyEvek(List<Diakosztalyev> diakOsztalyEvek) {
//        this.diakOsztalyEvek = diakOsztalyEvek;
//    }
//    
    public Diakosztalyev getKivalasztottDiakOsztalyev() {
        return kivalasztottDiakOsztalyEv;
    }

    public void setKivalasztottDiakOsztalyev(Diakosztalyev kivalasztottDiakOsztalyev) {
        this.kivalasztottDiakOsztalyEv = kivalasztottDiakOsztalyev;
    }

    public Integer getKivalasztottDiakId() {
        if (kivalasztottDiak == null) {
            return null;
        } else {
            return kivalasztottDiak.getId();
        }
    }

    public void setKivalasztottDiakId(Integer kivalasztottDiakId) {
        kivalasztottDiakOsztalyEv = null;
        kivalasztottDiakKonyv = null;
        diakkonyvek = null;
        if (kivalasztottDiakId != null) {
            this.kivalasztottDiak = dao.getDiak(kivalasztottDiakId);
        } else {
            this.kivalasztottDiak = null;
        }
    }

    public Diak getKivalasztottDiak() {
        return kivalasztottDiak;
    }

    public void setKivalasztottDiak(Diak kivalasztottDiak) {
        this.kivalasztottDiak = kivalasztottDiak;
    }

    public List<Diak> getDiakok() {
        return diakok;
    }

//    public void setDiakok(List<Diak> diakok) {
//        this.diakok = diakok;
//    }
//    public List<Diakkonyv> getDiakKonyvek() {
//        return diakKonyvek;
//    }
//
//    public void setDiakKonyvek(List<Diakkonyv> diakKonyvek) {
//        this.diakKonyvek = diakKonyvek;
//    }
    //AJAX függvények
    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return null;
    }

    public String ujDiak() {
        kivalasztottDiak = new Diak();
        return null;
    }

    public String mentDiak() {
        dao.saveOrUpdateDiak(kivalasztottDiak);
        diakok = updateDiakok();
        return null;
    }

    public String torolDiak() {
        dao.deleteDiak(kivalasztottDiak);
        diakok = updateDiakok();
        kivalasztottDiak = null;
        return null;
    }

    public List<Diakosztalyev> getDiakosztalyevs() {
        if (kivalasztottDiak != null && kivalasztottDiak.getDiakosztalyevs() != null) {
            List<Diakosztalyev> diakosztalyevs = new ArrayList<>(kivalasztottDiak.getDiakosztalyevs());
            diakosztalyevs.sort(new Comparator<Diakosztalyev>() {
                @Override
                public int compare(Diakosztalyev o1, Diakosztalyev o2) {
                    return o1.getTanev().compareTo(o2.getTanev());
                }
            });
            return diakosztalyevs;
        }
        return null;
    }

    public String ujDiakOsztalyev() {
        kivalasztottDiakOsztalyEv = new Diakosztalyev();
        kivalasztottDiakOsztalyEv.setDiak(kivalasztottDiak);
        konyvBean.updateKonyvek();  //nem frissítik a könyvek listáját, még mindig megjelennek
        konyvBean.getKonyvek();
        return null;
    }

    public String mentDiakOsztalyev() {
        dao.saveOrUpdateDiakosztalyev(kivalasztottDiakOsztalyEv);
        kivalasztottDiak = dao.getDiak(kivalasztottDiak.getId());   //újra lekér a diákot, mert megváltoztak az évei
//        diakOsztalyEvek = dao.getDiakosztalyevek(kivalasztottDiak);
        return null;

//        System.out.println(kivalasztottOsztalyev.getOsztaly());
//        System.out.println(kivalasztottOsztalyev.getTanev());
//        dao.saveOrUpdateOsztalyev(kivalasztottOsztalyev);
//        Diakosztalyev diakosztalyev = new Diakosztalyev();
//        diakosztalyev.setDiak(kivalasztottDiak);
//        diakosztalyev.setOsztalyev(kivalasztottOsztalyev);
//        dao.saveOrUpdateDiakosztalyev(diakosztalyev);
//        //újra lekérjük a diákot -> megváltozhatott az osztályév
//        kivalasztottDiak = dao.getDiak(kivalasztottDiak.getId());
    }

    public String torolDiakOsztalyev() {
        dao.deleteDiakosztalyev(kivalasztottDiakOsztalyEv);
        kivalasztottDiak = dao.getDiak(kivalasztottDiak.getId());   //újrakér, mert megváltoztak az évei
        kivalasztottDiakOsztalyEv = null;
        return null;
    }

    public String selejtez() {
        Diakkonyv dk = diakkonyvek.getRowData();
        dao.deleteDiakkonyv(dk);
        getDiakkonyvek();
        //System.out.println(dk.getKonyv().getCim());
        return null;
    }

src/java/tankonyv/KonyvBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tankonyv;

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import pojo.Diak;
import pojo.Diakkonyv;
import pojo.Konyv;
import pojo.Targy;

/**
 *
 * @author nbalazs
 */
@ManagedBean(name = "konyvBean")
@SessionScoped
public class KonyvBean {

    //private Integer kivalasztottTargyId;
    private Targy kivalasztottTargy;
    private Konyv kivalasztottKonyv;
    private String kodReszlet;
    private Dao dao;
    private DataModel<Konyv> konyvek;
    private DataModel<Diakkonyv> diakkonyvek;
    //private DataModel<Konyv> konyvek;
    //private List<Konyv> konyvek;
    private List<Targy> targyak;

    public Integer getKivalasztottTargyId() {
        if (kivalasztottTargy == null) {
            return null;
        } else {
            return kivalasztottTargy.getId();
        }
    }

    public String getKodReszlet() {
        return kodReszlet;
    }

    public void setKodReszlet(String kodReszlet) {
        this.kodReszlet = kodReszlet;
        konyvek = new ListDataModel<Konyv>(dao.getKonyvek(kivalasztottTargy, kodReszlet));
    }
    
    public String csakGomb(){
        System.out.println("Hello");
        return null;
    }
    
    public void setKivalasztottTargyId(Integer kivalasztottTargyId) {
        if (kivalasztottTargyId != null) {
            this.kivalasztottTargy = dao.getTargy(kivalasztottTargyId);
        } else {
            this.kivalasztottTargy = null;
        }
        konyvek = new ListDataModel<Konyv>(dao.getKonyvek(kivalasztottTargy, kodReszlet));
        kivalasztottKonyv = null;
    }

    public Targy getKivalasztottTargy() {
        return kivalasztottTargy;
    }
    
    public Integer getKivalasztottKonyvTargyId() {
        if (kivalasztottKonyv == null || kivalasztottKonyv.getTargy() == null) {
            return null;
        } else {
            return kivalasztottKonyv.getTargy().getId();
        }
    }

    public void setKivalasztottKonyvTargyId(Integer kivalasztottTargyId) {
            if (kivalasztottTargyId != null && kivalasztottTargyId != 0) {
                kivalasztottKonyv.setTargy(dao.getTargy(kivalasztottTargyId));
                //this.kivalasztottKonyv.setTargy();
                //this.kivalasztottKonyv = dao.getKonyv(kivalasztottKonyvId);
            } else {
                kivalasztottKonyv.setTargy(null);
            }
    }

    public Integer getKivalasztottKonyvId() {
        if (kivalasztottKonyv == null) {
            return null;
        } else {
            return kivalasztottKonyv.getId();
        }
    }

    public void setKivalasztottKonyvId(Integer kivalasztottKonyvId) {
        if (kivalasztottKonyvId != null) {
            this.kivalasztottKonyv = dao.getKonyv(kivalasztottKonyvId);
        } else {
            this.kivalasztottKonyv = null;
        }
    }

    public Konyv getKivalasztottKonyv() {
        return kivalasztottKonyv;
    }

    public void setKivalasztottKonyv(Konyv kivalasztottKonyv) {
        this.kivalasztottKonyv = kivalasztottKonyv;
    }

    public DataModel<Konyv> getKonyvek() {
        return konyvek;
    }

    public List<Targy> getTargyak() {
        return targyak;
    }
    
    public void updateKonyvek(){
        konyvek = new ListDataModel<Konyv>(dao.getKonyvek());
    }

    public DataModel<Diakkonyv> getDiakkonyvek() {
        if (kivalasztottKonyv != null){
            List<Diakkonyv> list = dao.getDiakkonyvek(kivalasztottKonyv);
            diakkonyvek = new ListDataModel<Diakkonyv>(list);
            return diakkonyvek;
        } 
        return null;
    }

    
    

    //AJAX függvények
    public String ujKonyv() {
        kivalasztottKonyv = new Konyv();
        return null;
    }

    public String mentKonyv() {

        dao.saveOrUpdateKonyv(kivalasztottKonyv);
        konyvek = new ListDataModel<Konyv>(dao.getKonyvek());
        return null;
    }

    public String torolKonyv() {
        dao.deleteKonyv(kivalasztottKonyv);
        konyvek = new ListDataModel<Konyv>(dao.getKonyvek());
        kivalasztottKonyv = null;
        return null;
    }

    public String ujTargy() {
        kivalasztottTargy = new Targy();
        return null;
    }

    public String mentTargy() {
        dao.saveOrUpdateTargy(kivalasztottTargy);
        targyak = dao.getTargyak();
        return null;
    }

    public String torolTargy() {
        //System.out.println(kivalasztottKonyv.getTargy().getKonyvs().size());
        if (kivalasztottTargy.getKonyvs().size() <= 1) {
            dao.deleteTargy(kivalasztottTargy);
            targyak = dao.getTargyak();
            kivalasztottTargy = null;
        }
        return null;
    }

    /**
     * Creates a new instance of KonyvBean
     */
    public KonyvBean() {
        dao = new Dao();
        konyvek = new ListDataModel<Konyv>(dao.getKonyvek());
        targyak = dao.getTargyak();
    }

}

web/diak.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="style.css"  /> 
    </h:head>
    <h:body>

        <h:form id="myForm">
            <div id="fejlec">
                <ui:insert name="fejlec" >
                    <ui:include src="fejlec.xhtml" />
                </ui:insert>
            </div>
            <div id="diakEvLenyiloDiaklistazashoz">
                <ui:insert name="diakEvLenyiloDiaklistazashoz" >
                    <ui:include src="diakEvLenyiloDiaklistazashoz.xhtml" />
                </ui:insert>
            </div>
            <div id="diakOsztalyEvLenyiloDiaklistazashoz">
                <ui:insert name="diakOsztalyEvLenyiloDiaklistazashoz" >
                    <ui:include src="diakOsztalyEvLenyiloDiaklistazashoz.xhtml" />
                </ui:insert>
            </div>
            
            <div id="diakLenyilo">
                <ui:insert name="diakLenyilo" >
                    <ui:include src="diakLenyilo.xhtml" />
                </ui:insert>
            </div>
            <div id="diakReszletek">
                <ui:insert name="diakReszletek" >
                    <ui:include src="diakReszletek.xhtml" />
                </ui:insert>
            </div>
            <div id="diakOsztalyEvLista">
                <ui:insert name="diakOsztalyEvLista" >
                    <ui:include src="diakOsztalyEvLista.xhtml" />
                </ui:insert>
            </div>
            <div id="diakOsztalyEvReszletek">
                <ui:insert name="diakOsztalyEvReszletek" >
                    <ui:include src="diakOsztalyEvReszletek.xhtml" />
                </ui:insert>
            </div>
            <!--            <div id="diakKonyvLista">
                            <ui:insert name="diakKonyvLista" >
                                <ui:include src="diakKonyvLista.xhtml" />
                            </ui:insert>
                        </div>-->
            <div id="diakKonyvTabla">
                <ui:insert name="diakKonyvTabla" >
                    <ui:include src="diakKonyvTabla.xhtml" />
                </ui:insert>
            </div>
            <ui:fragment rendered="#{diakBean.kivalasztottDiakOsztalyev != null and diakBean.kivalasztottDiakOsztalyev.osztaly != null}">
                <div id="targyLenyilo">
                    <ui:insert name="targyLenyilo" >
                        <ui:include src="targyLenyilo.xhtml" />
                    </ui:insert>
                </div>
                <div id="kodKereso">
                    <ui:insert name="kodKereso" >
                        <ui:include src="kodKereso.xhtml" />
                    </ui:insert>
                </div>
                <div id="diakKonyvTablaDiak">
                    <ui:insert name="diakKonyvTablaDiak">
                        <ui:include src="diakKonyvTablaDiak.xhtml" />
                    </ui:insert>
                </div>
            </ui:fragment>

        </h:form>
    </h:body>
</html>

web/diakEvLenyiloDiaklistazashoz.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <h:selectOneMenu 
                value="#{diakBean.kivalasztottEvDiaklistazashoz}"
                id="diakEvLenyiloDiaklistazashoz">
                <f:selectItem itemLabel="-Válassz tanévet!-" />
                <f:selectItems value="#{diakBean.evekDiaklistazashoz}" var="diak"
                               itemLabel="#{diak}" itemValue="#{diak}" />
                <f:ajax render="@form" />
            </h:selectOneMenu>
        </ui:composition>
    </h:body>
</html>

web/diakKonyvTabla.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <h:dataTable value="#{diakBean.diakkonyvek}" var="diakKonyv">
                <h:column>    				
                    <f:facet name="header">Cím</f:facet>   
                    <h:outputText value="#{diakKonyv.konyv.cim}" />                   
                </h:column>
                <h:column>
                    <f:facet name="header">Selejt</f:facet>
                    <h:commandButton value="Selejt"
                                     action="#{diakBean.selejtez()}">
                        <f:ajax render="@form" />
                    </h:commandButton>
                </h:column>
                <h:column>
                    <f:facet name="header">Visszahoz</f:facet>
                    <h:commandButton value="Visszahoz"
                                     action="#{diakBean.visszahoz()}">
                        <f:ajax render="@form" />
                    </h:commandButton>
                </h:column>
            </h:dataTable>
            <h:commandButton
                action="#{diakBean.pdfKeszit}" 
                value="PDF készítés">
                
            </h:commandButton> 
<!--            <h:commandButton value="Felvesz"
                             action="#{szamlaBean.kosarbeTesz}">
                <f:ajax render="@form" />
            </h:commandButton>
            <h:selectOneListbox
                value="#{diakBean.kivalasztottDiakKonyvId}"
                id="konyvLista">
                <f:selectItem itemLabel="-Mind-" />
                <f:selectItems value="#{diakBean.kivalasztottDiakOsztalyev.diakkonyvs}" var="diakKonyv"
                               itemLabel="#{diakKonyv.konyv.cim}" 
                               itemValue="#{diakKonyv.id}" />
                <f:ajax render="@form" />
            </h:selectOneListbox>-->
        </ui:composition>
    </h:body>
</html>

web/diakKonyvTablaDiak.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="styles.css"  /> 
    </h:head>
    <h:body>
        <ui:composition>
            <h:dataTable value="#{konyvBean.konyvek}" var="konyv"
                         name="diakKonyvTablaDiak"
                         styleClass="konyvTabla"
                         headerClass="konyvTablaHeader"
                         rowClasses="konyvTablaOddRow,konyvTablaEvenRow"
                         columnClasses="kodOszlop,cimOszlop,dbOszlop,kiveszOszlop">
                <h:column>    				
                    <f:facet name="header">Kód</f:facet>   
                    <h:outputText value="#{konyv.kod}" />                   
                </h:column>
                <h:column>    				
                    <f:facet name="header">Cím</f:facet>   
                    <h:outputText value="#{konyv.cim}" />                   
                </h:column>
                <h:column>    				
                    <f:facet name="header">DB könyvtár</f:facet>   
                    <h:outputText value="#{konyv.dbKonyvtarban}" />                   
                </h:column>
                <h:column>
                    <f:facet name="header">Kivesz</f:facet>
                    <h:commandButton value="Kivesz" 
                                     disabled="#{konyv.dbKonyvtarban == 0}"
                                     action="#{diakBean.kivesz()}">
                        <f:ajax render="@form" />
                    </h:commandButton>
                </h:column>
            </h:dataTable>
        </ui:composition>
    </h:body>
</html>

web/diakOsztalyEvLenyiloDiaklistazashoz.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <h:selectOneMenu 
                value="#{diakBean.kivalasztottOsztalyDiaklistazashoz}"
                id="diakOsztalyEvLenyiloDiaklistazashoz">
                <f:selectItem itemLabel="-Válassz osztályt!-" />
                <f:selectItems value="#{diakBean.diakOsztalyEvekDiaklistazashoz}" var="doe"
                               itemLabel="#{doe}" itemValue="#{doe}" />
                <f:ajax render="@form" />
            </h:selectOneMenu>
        </ui:composition>
    </h:body>
</html>